language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - which find-spark-home
  - source find-spark-home && echo $SPARK_HOME
  - source find-spark-home && pytest