language: python
dist: xenial
python:
  - "3.6"

install:
  - pip install -r requirements.txt --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
  - pip install -r requirements-dev.txt --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
  - pip install . --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
  - python scripts/get-jars.py

script:
  # Spark requires Java 8 (but xenial uses Java 11 by default)
  - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  # Run tests
  - pytest