language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt --extra-index-url https://anonymous@artifactory.vgt.vito.be/api/pypi/python-packages-public
# command to run tests
script:
  - SPARK_HOME=$(find_spark_home.py) pytest