class EVAL_ENV_KEY:
    VAULT_TOKEN = "vault_token"
    SENTINEL_HUB_CLIENT_ALIAS = "sentinel_hub_client_alias"
    MAX_SOFT_ERRORS_RATIO = "max_soft_errors_ratio"
    DEPENDENCIES = "dependencies"
    PYRAMID_LEVELS = "pyramid_levels"
    REQUIRE_BOUNDS = "require_bounds"
    CORRELATION_ID = "correlation_id"
    USER = "user"
    ALLOW_EMPTY_CUBES = "allow_empty_cubes"
    DO_EXTENT_CHECK = "do_extent_check"
