#!/bin/bash

if [ -z "$1" ]; then
    echo "First argument should be the path to the process graph. For example:"
    echo "'$0 path/to/process_graph.json'"
    exit 1
fi
if [ ! -f "$1" ]; then
    echo "File not found: $1"
    exit 1
fi

parent_folder="$(dirname "$1")"

export extra_arguments=()
if [ -n "$2" ]; then
    echo Mounting folder: "$2"
    if [ ! -d "$2" ]; then
        echo "Folder not found: $2"
        exit 1
    fi
    extra_arguments=(-v "$2":"$2":ro)
fi

# --entrypoint /bin/bash
# Specify user otherwise output files are root
# /etc/passwd to avoid "whoami: cannot find name for user ID"
# Opening a /vsi file with the netCDF driver requires Linux userfaultfd to be available. If running from Docker, --security-opt seccomp=unconfined might be needed.
# mount is used to read process_graph and write results
# Avoid -i, to avoid "the input device is not a TTY"
# --network host can fix internet connection when the host machine is behind a VPN
docker run -t \
    --user "$(id -g):$(id -u)" \
    -v /etc/passwd:/etc/passwd:ro \
    --security-opt seccomp=unconfined \
    -v "$parent_folder":/opt/docker_mount \
    "${extra_arguments[@]}" \
    --network host \
    openeo_docker_local
