#!/bin/bash

if [ -z "$1" ]; then
    echo "First argument should be the path to the process graph. For example:"
    echo "'$0 path/to/process_graph.json folder/that/contains/local/stac/catalogs/'"
    exit 1
fi
if [ ! -f "$1" ]; then
    echo "File not found: $1"
    exit 1
fi

graph_path=$(realpath "$1")
graph_directory="$(dirname "$graph_path")"
graph_filename=$(basename -- "$graph_path")

export extra_arguments=()
if [ -n "$2" ]; then
    if [ ! -d "$2" ]; then
        echo "Folder not found: $2"
        exit 1
    fi
    extra_mount_realpath=$(realpath "$2")
    extra_arguments=(-v "$extra_mount_realpath":"$extra_mount_realpath":ro)
fi

# --entrypoint /bin/bash
# Specify user otherwise output files are root
# /etc/passwd to avoid "whoami: cannot find name for user ID"
# Opening a /vsi file with the netCDF driver requires Linux userfaultfd to be available. If running from Docker, --security-opt seccomp=unconfined might be needed.
# mount is used to read process_graph and write results
# Avoid -i, to avoid "the input device is not a TTY"
# --network host can fix internet connection when the host machine is behind a VPN
# --rm to remove the container after it finishes. Remove all stopped containers with `docker container prune -f && docker ps -a`
docker run -t \
    --security-opt seccomp=unconfined \
    -v "$graph_directory":/opt/docker_mount \
    "${extra_arguments[@]}" \
    --network host \
    --rm \
    openeo_docker_local \
    "$graph_filename"
